### ISSUE TITLE
panicked error on new stratum connection

### ISSUE THREAD

**Issue by devfans** [TheBlueMatt/mining-proxy#15]
Seems we met a panic exception with pool-proxy when a new stratum connected is established:
The output:
```
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
Got new client connection (id 120)
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
Got new client connection (id 121)
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
Got new client connection (id 122)
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
Got new client connection (id 123)
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
Got new client connection (id 124)
thread 'tokio-runtime-worker-1' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
Got new client connection (id 125)
thread 'tokio-runtime-worker-0' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', libcore/result.rs:945:5
```

Panicked points:
+ `             at src/pool_client.rs:139`
+ `             at src/pool_client.rs:171`
+ `             at src/pool_client.rs:312`
+ `             at src/stratum_server.rs:742`
+ `             at src/stratum_server.rs:966`
+ `             at src/stratum_server.rs:794`
+ `             at src/stratum_server.rs:493`
+ `             at src/stratum_server.rs:352`
+ `             at src/multi_user_proxy.rs:131`
+ `             at src/work_client.rs:420`

**Comment by TheBlueMatt** [comment]
Can you run with RUST_BACKTRACE=1 and get the actual backtrace? Also, I meant to turn on panic=abort, should do that.

**Comment by devfans** [comment]
Sure, i will try this tomorrow morning, normally dropping a user for failed authentication will reproduce the issue.

**Comment by devfans** [comment]
Agree，thanks for fix 👍
